[workspace]
members = [
    "./benches",
    "./source",
    "./prepare",
    "./composing/0_base",
    "./composing/1_base",
    "./composing/2_opt",
    "./tests",
]
resolver = "2"

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3
